### ISSUE TITLE
Create AGGREGATION QUERIES

### ISSUE THREAD

**Issue by Sojer23** [Sojer23/ASAS18-Explorer-CloudTeam#6]
Detect de queries needed.
Study the aggregations.

Mongoose Aggregation (https://mongoosejs.com/docs/api.html#Aggregate)

**Comment by Sojer23** [comment]
Follow the documentation of the class, it has the same examples to use in this project.
The code of those sessions is also available.

**Comment by Sojer23** [comment]
Missing two aggregations, we have to check if all works correctly.
- averagePriceFinderStats
- topKeywordsFinderStats

**Comment by migcassan** [comment]
not sure if will be able to complete the missing twos by today.
