### ISSUE TITLE
Create Controller/model/route for set GlobalConfig

### ISSUE THREAD

**Issue by Sojer23** [Sojer23/ASAS18-Explorer-CloudTeam#7]

**Comment by Sojer23** [comment]
Our global configuration has:
-

**Comment by Sojer23** [comment]
![image](https://user-images.githubusercontent.com/10140897/54884421-2de89900-4e71-11e9-85b0-3493efb4e358.png)

**Comment by Sojer23** [comment]
Added PUT methods, more validation and postman collections.

**Comment by migcassan** [comment]
Completed
